### ISSUE TITLE
Skystone Match Details

### ISSUE THREAD

**Issue by CrispyBacon1999** [orange-alliance/TOA-Flutter#8]
The models for Skystone will need to be added in for this year's game. I've started work on implementing them to match the data layout from [the web app](https://github.com/orange-alliance/the-orange-alliance).
[SkystoneMatchDetails.ts](https://github.com/orange-alliance/the-orange-alliance/blob/master/src/app/models/game-specifics/SkystoneMatchDetails.ts)
[SkystoneAllianceDetails.ts](https://github.com/orange-alliance/the-orange-alliance/blob/master/src/app/models/game-specifics/SkystoneAllianceDetails.ts)

**Comment by ofekashery** [comment]
Hey @CrispyBacon1999, we're working on that (#7) and hope to release an update later this week

**Comment by CrispyBacon1999** [comment]
Oh good call, didn't see that it was in there already.
